# Generated by Django 5.2.12 on 2026-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='opening_time',
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
