# Generated by Django 5.2.12 on 2026-03-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_options_clinic_appointment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='appointment_mode',
        ),
    ]
