# Generated by Django 5.2.12 on 2026-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clinic_closing_time_remove_clinic_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'token_number']},
        ),
        migrations.AddField(
            model_name='clinic',
            name='appointment_mode',
            field=models.CharField(choices=[('walkin', 'Walk-in Token'), ('timed', 'Timed Appointment')], default='walkin', max_length=20),
        ),
    ]
